name: Build and deploy Mensenlinq Wordpress module
on:
    pull_request:
        branches: 
            - main
            - dev
        types: [closed]
jobs: 
    deploy_to_staging:
        runs-on: ubuntu-latest
        environment: Staging
        steps: 
            - run: echo "Merged to staging branch"


    deploy_to_production:
        runs-on: ubuntu-latest
        environment: Production
        steps: 
            - run: echo "Merged to production branch"