name: Build and deploy Mensenlinq Wordpress module
on:
    pull_request:
        branches: 
            - main
            - dev
        types: [closed]
jobs: 
    Explore-Github-Actions:
        runs-on: ubuntu-latest
        steps: 
            - run: echo "Test Merged with Dev or Main"